<?php

/**
 * PluginUserActivationCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUserActivationCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUserActivationCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUserActivationCode');
    }
}