all:
  doAuth:
    # password encrypting algorithm
    algorithm_callable: sha1
    # function for delegating password check
    check_password_callable: false
    # coookie 
    remember_cookie:
      name: doRemember
      # expiration time (in secs), currently 1 year
      expiration_age: 31536000
      
    register:
      # where to redirect valid user after registration
      redirect_path: '@homepage'
      # auto sign in after registration
      sign_in: true
      
    # use user activation
    activation: false

    reset_password:
      # where to redirect after request for password reset
      url: '@homepage'

    email:
      # activate by email if activation is on
      activation: true
      # send registration notification
      registration: true
      # sender email
      from: mailer@currenthost.com
      # module where email partials are stored.
      # default is module from controller
      module: false

    signin:
      # signin redirect
      url: '@homepage'

    signout:
      #signout url
      url: '@homepage'